package gridsim.fta;

import gridsim.fta.FailureEvent;

import java.util.List;


/**
 * This interface defines what a Failure model should provide. A failure
 * model generates a list of availability/unavailability that can be happened in a resource (e.g., a PE)
 * 
 *
 * @author   Bahman Javadi
 * @since    GridSim Toolkit 5.0
 * 
 * @see FailureFileReader
 */
public interface FailureModel {
	
	/**
	 * Returns a list with the jobs generated by the workload.
	 * @return a list with the jobs generated by the workload.
	 */
	List<FailureEvent> generateFailure();	
	
}
